language: go

go:
  - '1.12'
  - '1.13'
  - '1.14'
  - 'tip'

jobs:
  include:
    - stage: "Check"
      go: '1.14'
      before_script: cd /tmp && go get -u github.com/elastic/go-licenser@master
      script: .ci/check.sh
    - stage: "Test"
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

stages:
  - Check
  - Test

after_success:
  - bash <(curl -s https://codecov.io/bash)
