language: go


jobs:
  include:
    - stage: "Check"
      go: '1.14'
      before_script: ./.ci/goinstall.sh github.com/elastic/go-licenser@master
      script: .ci/check.sh
    - stage: "Test"
      go:
        - '1.12'
        - '1.13'
        - '1.14'
        - 'tip'
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

stages:
  - Check
  - Test

after_success:
  - bash <(curl -s https://codecov.io/bash)
