#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'ubuntu-18 && immutable' }
  environment {
    REPO = "go-ucfg"
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    JOB_GIT_CREDENTIALS = "f6c7695a-671e-4f4f-a331-acdce44ff9ba"
    PIPELINE_LOG_LEVEL = 'INFO'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger('(?i)(.*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*|^\\/test$)')
  }
  stages {
    stage('Checkout') {
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}")
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Check') {
      steps {
        withGithubNotify(context: 'Check') {
          cleanup()
          withMageEnv(version: '1.14'){
            dir("${BASE_DIR}"){
              sh(label: 'go-licenser', script: '.ci/goinstall.sh github.com/elastic/go-licenser@master')
              sh(label: 'go-licence-detector', script: '.ci/goinstall.sh go.elastic.co/go-licence-detector')
              sh(label: '.ci/check.sh', script: '.ci/check.sh')
            }
          }
        }
      }
    }
    stage('Test') {
      failFast false
      matrix {
        agent { label 'ubuntu-18 && immutable' }
        options { skipDefaultCheckout() }
        axes {
          axis {
            name 'GO_VERSION'
            values '1.13', '1.14', '1.15'
          }
        }
        stages {
          stage('Test') {
            steps {
              withGithubNotify(context: "Test-${GO_VERSION}") {
                cleanup()
                withGoEnv(version: "${GO_VERSION}"){
                  dir("${BASE_DIR}"){
                    sh(label: 'test', script: '.ci/test.sh')
                  }
                }
              }
            }
            post {
              always {
                archive "${BASE_DIR}/build/**"
                junit(allowEmptyResults: true, keepLongStdio: true, testResults: "${BASE_DIR}/build/*xml")
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
  }
}

def cleanup(){
  dir("${BASE_DIR}"){
    deleteDir()
  }
  unstash 'source'
}
